config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root   'posts#index'
  get    'posts'          => 'posts#index'
  get    'posts/new'      => 'posts#new'
  post   'posts'          => 'posts#create'
  get    'posts/:id/edit' => 'posts#edit'
  patch  'posts'          => 'posts#update'
  delete 'posts/:id'      => 'posts#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  validates :text, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :move_to_index, except: [:index]
  
  def index
    @posts = Post.all.order("created_at DESC")
  end 

  def new
    @post = Post.new
  end

  def create
    redirect_to root_path unless (Post.create(post_params)).save
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    Post.find(params[:post][:id]).update(post_params)
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy if post.user_id == current_user.id
  end
  
  private
  def post_params
    params.require(:post).permit(:text).merge(user_id: current_user.id)
  end

  def move_to_index
    redirect_to action: :index unless user_signed_in?
  end  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ぶろぐ</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body data-turbolinks="false">
    <header>
        <h1 class = "header_logo">
          <%= link_to "ぶろぐ","/" %>
        </h1>
      <% if user_signed_in? %>
        <div class = "header_button">
          <%= link_to "とうこう", posts_new_path, class: "button", remote: true %>
          <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "button" %>
        </div>  
      <% else %>
        <div class = "header_button">
          <%= link_to "ログイン", new_user_session_path, class: "button" %>
          <%= link_to "とうろく", new_user_registration_path, class: "button"%>
        </div>  
      <% end %>
    </header>
    <%= yield %>
  </body>
  <div id="dl" style="display:none;">
    <span class="ui-helper-hidden-accessible"><input type="image"/></span>
    <p>ほんとうに けしますか？</p>
  </div>
</html>

app/views/posts/_edit.html.erb
  <h1 class = "edit_logo">へんしゅうする</h1>
  <%= form_for(@post, url: posts_path, remote: true) do |f| %>
    <% if current_user.id == @post.user_id %>
      <%= f.submit :class => "complet_button", :value => "かんりょう" %>
    <% end %>
    <%= f.text_area :text, class: "edit_textarea" %>
    <%= f.hidden_field :id, :value => @post.id %>
  <% end %>
</div>

<script>$('.edit_textarea').focus();</script>

app/views/posts/_new.html.erb
<h1 class = "new_post_logo">とうこうをかく</h1>
  <%= form_for(@post, remote: true) do |f| %>
  <%= f.submit :class => "new_post_button", :value => "とうこうする" %>
  <%= f.text_area :text, placeholder: "なにかかいてね", class: "new_post_textarea" %>
<% end %>

<script>$('.new_post_textarea').focus();</script>

app/views/posts/_post.html.erb
<div class = "post_area">
  <%= simple_format(post.text) %>
  <% if user_signed_in? && current_user.id == post.user_id %>
    <div class = "post_area_button">
      <%= link_to "へんしゅう", "/posts/#{post.id}/edit", method: :get, remote: true, class: "edit_button" %>
      <%= link_to 'さくじょ', "/posts/#{post.id}", method: :delete, class: "delete_button", data: {post_id: post.id} %>
    </div>
  <% end %>
</div>

app/views/posts/create.js.erb
$(".contents").html(`<div class = "confirmation">
                      <h1>
                        とうこうが かんりょう しました
                      </h1>
                        <%= link_to "とうこうがめんへ", "/", class: "button" %>
                    </div>`)

app/views/posts/edit.html.erb
<div class = "contents">
  <%= render partial: "edit", locals: { post: @post }%>

app/views/posts/edit.js.erb
$(".contents").html("<%= escape_javascript(render "edit")%>")

app/views/posts/index.html.erb
<div class = "contents">
  <% @posts.each do |post| %>
    <%= render partial: "post", locals: { post: post }%>
  <% end %>
  <%# <script>
    $('.delete_button').click(function(){
      if(!confirm('本当に削除しますか？')){
        return false;
      }
    });
</script> %>
</div> 

app/views/posts/new.html.erb
<div class = "contents">
  <%= render partial: "new", locals: { post: @post }%>

app/views/posts/new.js.erb
$(".contents").html("<%= escape_javascript(render "new")%>")

app/views/posts/update.js.erb
$(".contents").html(`<div class="confirmation">
                      <h1>
                      へんしゅうが かんりょう しました
                      </h1>
                      <a id="return_index_button" class="button" href="/">とうこうがめんへ</a>
                    </div>`)